detectors:
  IrresponsibleModule:
    enabled: false
  DuplicateMethodCall:
    enabled: true
    max_calls: 2
  TooManyStatements:
    enabled: true
    max_statements: 10
  InstanceVariableAssumption:
    enabled: false

exclude_paths:
  - 'db/'
