plugins:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/**/*
    - config.ru
    - db/**/*

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

RSpec/ExampleLength:
  Max: 10

RSpecRails/InferredSpecType:
  Enabled: false
