services:
  hoa:
    image: 273058101644.dkr.ecr.us-east-1.amazonaws.com/hoa-prod:latest
    build:
      context: .
      platforms:
      - "linux/amd64"
    hostname: hoa
    restart: unless-stopped
    environment:
      - RAILS_ENV
      - HOA_DATABASE_URL
    ports:
      - 3000:3000
    network_mode: host
    logging:
      driver: awslogs
      options:
        awslogs-group: hoa
        awslogs-stream: hoa-logs
